name: hellama
description: Ollama integration for the Helix editor in a simple language server plugin.
version: 0.0.1
repository: https://github.com/nandoflorestan/hellama

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  http: ^1.4.0
  # lsp_server: ^0.3.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
